src/objects/Project_Review__c.object
<CustomObject>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sponsor_Email__c</fullName>
        <label>Sponsor Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Stakeholder_Sponser__c</fullName>
        <label>Stakeholder/Sponser</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Review</label>
    <nameField>
        <displayFormat>PROJ-{0000}</displayFormat>
        <label>Project Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/unifiedTest.cls
/*  
   Created By   :P.W.Tyler   
   Created Date :23rd October 2015
   Last Mod Date:
   Class Function: Creating test data
                   
                  
   Change History:
           
    
*/
@isTest
public class unifiedTest {

    public static Project_Review__c createProject(string projectName) {
       Project_Review__c project = new Project_Review__c();
       project.Project_Name__c=projectName;
       project.Status__c = 'Open';
       project.Stakeholder_Sponser__c='Joe King';
       project.Sponsor_Email__c = 'pwtyleruk@gmail.com';
       
       return project;
       
    }
}